---
- hosts: ismail
  vars_prompt:
<<<<<<< HEAD
   - name: "version skype 4"
=======
   - name: "version skype (3"
>>>>>>> 5ccb5b1466552e40dbc5a2bcba397fa3ef7f4c7b
     prompt: "quel version Skype voulez-vous installer?"
     private: no
   - name: "url"
     prompt: "quel est l'URL pour telecharger skype?"
     private: no
  roles:
    - role: skype-install
